### ISSUE TITLE
Scala Native 0.5?

### ISSUE THREAD

**Issue by mio-19** [eed3si9n/expecty#177]

**Comment by alexarchambault** [comment]
It'd be great to have a new release to get support for Scala Native 0.5 in a stable version 🙏

**Comment by keynmol** [comment]
@eed3si9n @Baccata I'll try to get SN0.5 working and will release as a minor-breaking release, hopefully today or tomorrow.

**Comment by keynmol** [comment]
Actually seems like this only needs a 0.17.0 release after #182
