### ISSUE TITLE
Allow for varags assertions

### ISSUE THREAD

**Issue by Baccata** [eed3si9n/expecty#25]
One thing from utest that is quite enjoyable is the ability to have several assertions in the same macro block : 

```
assert(
    a == 1,  
    b == 2 
)
```

It'd be great for Expecty to allow for the same UX

**Comment by eed3si9n** [comment]
I disagree. The second parameter of `assert(...)` should be custom error message to keep drop-in compatibility with the traditional assert.

**Comment by Baccata** [comment]
I see. I suppose it could still be provided as another method than "apply" on the Recorder class to avoid overloading conflicts : 

``` 
assert.multiple(
    a == 1, 
    b == 2 
)
```

**Comment by eed3si9n** [comment]
https://github.com/eed3si9n/expecty/pull/29
