### ISSUE TITLE
Publishing for 3.0.0-M2

### ISSUE THREAD

**Issue by keynmol** [eed3si9n/expecty#36]
Not a request, just creating this for tracking to make sure @eed3si9n doesn't already have it working :)

I've started a PR #35 but I'm flying blind with Scala 3 macros, so expect a lot of stupid stuff to happen in that PR.

**Comment by keynmol** [comment]
@eed3si9n if you're happy with my PR for 3.0.0-M3, would you mind publishing a new version?

**Comment by eed3si9n** [comment]
I should probably port the test and fix from https://github.com/scala/nanotest-strawman/commit/5762e6a19316236cb8e80347a93aa3a961ca2c78
