### ISSUE TITLE
Enable Scala Steward in this repo?

### ISSUE THREAD

**Issue by SethTisue** [eed3si9n/expecty#61]
@eed3si9n I can submit the PR if you say it's okay

thought prompted by #60, where I'm manually bumping versions

**Comment by eed3si9n** [comment]
Sure. I'm ok with it as long as we keep bincompat.

**Comment by SethTisue** [comment]
https://github.com/scala-steward-org/repos/pull/967 was merged

**Comment by SethTisue** [comment]
The first round of Steward PRs is in. I went through and hit "approve" on some and on others, recommended they be closed.
